/* Catalogue and quest pages are derived from docs/progression_manifest.json. */
module.exports = function campaignPages(manifest, artwork) {
  const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  const name=value=> {const raw=String(value), id=raw.replace(/^\d+x /,'').replace(/^#/,''); return (raw.match(/^(\d+)x /)?.[1] ? raw.match(/^(\d+)x /)[1]+' × ' : '')+(raw.startsWith('#')?'Any matching ':'')+(artwork.names[id] || id.split(':').at(-1).replace(/^tk3_/,'').replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase()));};
  const ingredient=value=>typeof value==='string'?`<span class="item-name">${esc(name(value))}</span><code class="technical">${esc(value)}</code>`:value.fluid?`${esc(value.amount)} mB ${esc(name(value.fluid))}<code class="technical">${esc(value.fluid)}</code>`:`<code>${esc(JSON.stringify(value))}</code>`;
  const methods={shaped:'Shaped crafting',shapeless:'Shapeless crafting',sequence:'Sequenced assembly',deploying:'Deploying',mixing:'Mixing',pressing:'Pressing',compacting:'Compacting',cutting:'Saw cutting',milling:'Milling',crushing:'Crushing',splashing:'Fan washing',haunting:'Haunting',smelting:'Furnace smelting',blasting:'Blast furnace',sandpaper_polishing:'Sandpaper polishing',apparatus:'Enchanting Apparatus',stonecutting:'Stonecutting',mechanical_crafting:'Mechanical crafting',enriching:'Enrichment',mek_enriching:'Mekanism enrichment',mek_smelting:'Mekanism smelting',ae_charger:'AE2 Charger',ae_print:'AE2 printing',ae_processor:'AE2 processor assembly',cauldron_brew:'Cauldron brewing',cauldron_empty:'Cauldron bottling',wrapped:'Preserving upgrade',native:'Native recipe / processing'};
  const recipeRow = recipe => {
    const keyed=recipe.inputs&&!Array.isArray(recipe.inputs);
    const ingredients=keyed?Object.entries(recipe.inputs).map(([key,value])=>`<div class="key"><b>${esc(key)}</b><div>${ingredient(value)}</div></div>`).join(''):recipe.inputs.map(ingredient).join('<span class="plus">+</span>');
    const conditions=[];
    if(recipe.pattern) conditions.push(`<pre class="pattern">${esc(recipe.pattern.join('\n')).replaceAll(' ','&#32;')}</pre>`);
    if(recipe.steps) conditions.push(`Ordered operations: ${recipe.steps.map(esc).join(' → ')}. One loop.`);
    if(recipe.tool||recipe.held_tool) conditions.push('Held tool: '+esc(name(recipe.tool||recipe.held_tool)));
    if(recipe.keep) conditions.push('Deployment catalyst is retained.');
    if(recipe.keep_steps) conditions.push('Retained deployment steps: '+esc(JSON.stringify(recipe.keep_steps)));
    if(recipe.heated) conditions.push('Heat: '+esc(recipe.heated));
    if(recipe.source) conditions.push('Source: '+esc(recipe.source));
    for(const key of ['base','fluid','fluid_output']) if(recipe[key]) conditions.push(`${key.replaceAll('_',' ')}: ${ingredient(recipe[key])}`);
    for(const key of ['chemical_inputs','chemical_outputs']) if(recipe[key]&&Object.keys(recipe[key]).length) conditions.push(`${key.replaceAll('_',' ')}: <code>${esc(JSON.stringify(recipe[key]))}</code>`);
    if(recipe.serializer) conditions.push('Serializer: <code>'+esc(recipe.serializer)+'</code>');
    return `<tr data-recipe-id="${esc(recipe.id)}" data-tier="${recipe.tier}" data-method="${recipe.kind}" data-search="${esc((name(recipe.output)+' '+JSON.stringify(recipe)).toLowerCase())}"><td><span class="tier-pill">${recipe.tier}</span></td><td>${ingredient(recipe.output)}</td><td>${esc(methods[recipe.kind]||name(recipe.kind))}<code class="technical recipe-id">${esc(recipe.id)}</code><a class="visual-link" href="../workshop/?recipe=${encodeURIComponent(recipe.id)}">Open recipe →</a></td><td>${ingredients}</td><td>${conditions.join('<br>')||'—'}</td></tr>`;
  };
  const catalogue=`<section id="recipes"><div class="controls"><label for="recipe-search">Search item, ingredient or recipe<input id="recipe-search" type="search" placeholder="Try kinetic mechanism, slime or casing…"></label><label for="tier-filter">Tier<select id="tier-filter"><option value="">All tiers</option>${manifest.chapters.map(chapter=>`<option value="${chapter.order_index}">Tier ${chapter.order_index}</option>`).join('')}</select></label><label for="method-filter">Process<select id="method-filter"><option value="">All processes</option>${[...new Set(manifest.recipes.map(recipe=>recipe.kind))].sort((a,b)=>methods[a].localeCompare(methods[b])).map(method=>`<option value="${method}">${methods[method]}</option>`).join('')}</select></label></div><div class="recipe-tools"><span id="recipe-count" role="status">${manifest.recipes.length} recipes</span><label><input id="show-ids" type="checkbox">Show item IDs</label><button id="expand-all" type="button">Expand all</button><button id="collapse-all" type="button">Collapse all</button><button id="clear-filters" type="button">Clear filters</button></div><p class="small">Authored T&K3 recipes, grouped by chapter. Native mechanics remain active where stated. The visual workshop also includes one separately labelled native Hopper Upgrade reference.</p><div id="recipe-groups" class="hide-ids">${manifest.chapters.map(chapter=>{const rows=manifest.recipes.filter(recipe=>recipe.tier===chapter.order_index);return `<details class="recipe-group"${chapter.order_index===1?' open':''}><summary>${esc(chapter.title)}<span class="count">${rows.length} recipes</span></summary><div class="table-wrap"><table class="recipe-table"><thead><tr><th>Tier</th><th>Output & yield</th><th>Process & walkthrough</th><th>Ingredients</th><th>Pattern & conditions</th></tr></thead><tbody>${rows.map(recipeRow).join('')}</tbody></table></div></details>`;}).join('')}</div><p id="no-results" class="empty" hidden>No matching recipes. Clear the filters or try another ingredient.</p></section>`;
  const allChapters=[...manifest.chapters,...(manifest.guide_chapters||[])];
  const quests=new Map(allChapters.flatMap(chapter=>chapter.quests.map(quest=>[quest.id,{...quest,chapter:chapter.order_index}])));
  const goal=task=>task.type==='item'?`${task.count||1} × ${esc(name(task.item.id))}`:task.type==='checkmark'?esc(task.title||'Complete the described setup'):task.type==='kill'?'Defeat '+esc(name(task.entity)):esc(task.title||task.type);
  const reward=value=>{if(value.type!=='item') return esc(value.type);const item=value.item;let label=name(item.id);try {const custom=item.components?.['minecraft:custom_name'];if(custom) label=JSON.parse(custom).text;} catch {}return `${value.count||1} × ${esc(label)}${item.components?.['minecraft:unbreakable']?' · Unbreakable':''}`;};
  const guidance=quest=>`<p class="small"><strong>◆ GOAL</strong><br>${esc(quest.goal||'Complete the goal below.')}</p>${quest.description.map(text=>`<p class="small">${esc(text)}</p>`).join('')}${quest.steps?.length?`<p class="small"><strong>◇ HOW TO</strong></p><ol class="small">${quest.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>`:''}${quest.tips?.length?`<p class="small"><strong>✦ TIP</strong><br>${quest.tips.map(esc).join('<br>')}</p>`:''}${quest.caution?`<p class="small"><strong>! WATCH OUT</strong><br>${esc(quest.caution)}</p>`:''}`;
  const chapterSection=chapter=>`<section class="chapter-section"><h3 id="chapter-${chapter.order_index}">${esc(chapter.title)}</h3><p class="muted">${esc(chapter.subtitle)} · <strong>${chapter.quests.length} QUESTS</strong></p><details${chapter.order_index===1||chapter.source_key==='tutorial'?' open':''}><summary>View goals, guidance & rewards</summary><div class="table-wrap"><table><thead><tr><th>Quest & guidance</th><th>Goal</th><th>Before this quest</th><th>Reward</th></tr></thead><tbody>${chapter.quests.map(quest=>`<tr id="quest-${quest.id}"><td><strong>${esc(quest.title)}</strong>${quest.optional?'<span class="technical">Optional branch</span>':''}${quest.quest_subtitle?`<span class="technical">${esc(quest.quest_subtitle)}</span>`:''}${guidance(quest)}</td><td>${quest.tasks.map(goal).join('<br>')}</td><td>${quest.dependencies.map(id=>`<a href="#quest-${id}">${esc(quests.get(id)?.title||id)}</a>`).join('<br>')||'Start here'}</td><td>${quest.rewards.map(reward).join('<br>')||'—'}</td></tr>`).join('')}</tbody></table></div></details></section>`;
  const groups=manifest.quest_groups||[{id:manifest.chapters[0].group,key:'mechanical',title:'Mechanical Quests'}];
  const chapterPage=`<section id="chapters"><p class="notice"><strong>${manifest.quest_count} QUESTS</strong> · <strong>10 PROGRESSION CHAPTERS</strong> · <strong>${manifest.guide_chapters?.length||0} GUIDE PAGES</strong><br>Follow the workshop campaign or choose a tutorial, character guide or optional project. Item and kill goals are detected in game; reading and activity checkmarks record your own progress. Class choices are personal investments in the skilltree.</p><div class="actions">${groups.map(group=>`<a class="button secondary" href="#category-${group.key}">${esc(group.title)}</a>`).join('')}</div>${groups.map(group=>{const chapters=allChapters.filter(chapter=>chapter.group===group.id);return `<section><h2 id="category-${group.key}">◆ ${esc(group.title.toUpperCase())}</h2><p class="muted"><strong>${chapters.length} PAGES</strong> · <strong>${chapters.reduce((count,chapter)=>count+chapter.quests.length,0)} QUESTS</strong></p><p>${chapters.map(chapter=>`<a href="#chapter-${chapter.order_index}">${esc(chapter.title)}</a>`).join(' · ')}</p>${chapters.map(chapterSection).join('')}</section>`;}).join('')}</section>`;
  return {catalogue,chapters:chapterPage,name,methods};
};
