/* Landing pages use the same page metadata as navigation and search. */
module.exports = function content(site, manifest) {
  const copy = require('./home.json');
  const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
  const page = route => site.config.pages.find(item => item.route === route);
  const card = (route, label, prefix = '') => {const item = page(route); return `<a class="card guide-card" data-category="${item.category}" href="${prefix + route}"><p class="eyebrow">${esc(label || site.config.groups.find(group => group.id === item.category).label)}</p><h3>${esc(item.title)}</h3><p>${esc(site.interpolate(item.summary))}</p><span class="card-action">Open guide <span aria-hidden="true">↗</span></span></a>`;};
  const home = `<section class="home-hero"><div class="hero-copy"><p class="eyebrow">${esc(copy.eyebrow)}</p><h1>${copy.titleLines.map(esc).join('<br>')}</h1><p class="hero-intro">${esc(copy.intro)}</p><div class="actions"><a class="button primary" href="3.0/">${esc(copy.primaryAction)} <span aria-hidden="true">→</span></a><a class="button secondary" href="guides/">${esc(copy.secondaryAction)}</a></div><p class="hero-note"><span class="status-dot" aria-hidden="true"></span> T&K3 is in development · Minecraft 1.21.1 · NeoForge</p></div><figure class="hero-art"><img src="assets/brand/${site.config.assets.banner}" width="1672" height="941" alt="Towns and Three Kingdoms: a moonlit mountain landscape, dragon and castle"><figcaption>${esc(copy.artCaption)}</figcaption></figure></section><div class="strip" aria-label="Current authored campaign"><div><b>${manifest.chapters.length}<strong>Chapters</strong></b><span>A connected workshop campaign</span></div><div><b>${manifest.recipes.length.toLocaleString('en-US')}<strong>Recipes</strong></b><span>Authored routes across tiers 1–10</span></div><div><b>${manifest.quest_count}<strong>Quests</strong></b><span>Goals, milestones and rewards</span></div></div><section class="home-section"><div class="section-top"><div><p class="eyebrow">Choose your next step</p><h2>${esc(copy.guidesTitle)}</h2></div><a href="guides/">Browse all guides <span aria-hidden="true">→</span></a></div><div class="card-grid">${card('progression/','01 · Start your workshop')}${card('recipes/','02 · Look up a recipe')}${card('automation/','03 · Build a reliable factory')}${card('3.0/magic/','04 · Explore the arcane')}${card('3.0/kingdoms/','05 · Grow your settlement')}${card('chapters/','06 · Follow the campaign')}</div></section><section class="version-choice"><div><p class="eyebrow">Two packs. Clear documentation.</p><h2>${esc(copy.versionTitle)}</h2><p>${esc(copy.versionIntro)}</p></div><div class="version-cards"><a href="3.0/"><span class="version-tag">T&K3</span><h3>The new adventure</h3><p>Minecraft 1.21.1 · NeoForge<br>In development</p><span class="card-action">Explore T&K3 →</span></a><a href="2.0/"><span class="version-tag legacy">T&K2</span><h3>The original archive</h3><p>Historical pack documentation<br>All 11 original wiki pages preserved</p><span class="card-action">Open the archive →</span></a></div></section>`;
  const guides = `<section id="find-guide" class="guide-finder"><label for="guide-search">Find a guide by title, topic or system</label><input id="guide-search" type="search" placeholder="Try storage, magic, chapter or mod…"><div class="guide-filters" role="group" aria-label="Filter guides"><button type="button" data-guide-filter="" aria-pressed="true">All topics</button>${site.config.groups.map(group => `<button type="button" data-guide-filter="${group.id}" aria-pressed="false">${esc(group.label)}</button>`).join('')}</div><p id="guide-count" role="status"></p></section><div class="guide-sections">${site.config.groups.map(group => `<section class="guide-category" data-guide-category="${group.id}"><h2>${esc(group.label)}</h2><div class="card-grid">${site.config.pages.filter(item => item.category === group.id && item.route && item.route !== 'guides/' && item.menu !== false).map(item => `<div class="guide-entry" data-guide-text="${esc((item.title+' '+item.summary).toLowerCase())}">${card(item.route, group.label, '../')}</div>`).join('')}</div></section>`).join('')}</div><p id="guide-empty" class="notice" hidden>No guides found. Try a broader search or choose all topics.</p>`;
  return {home, guides};
};
