// Deterministic documentation rendering. Data records keep their own provenance.
module.exports = function(data) {
  const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  const rows=(heads,values)=>'\n\n| '+heads.join(' | ')+' |\n|'+heads.map(()=> '---').join('|')+'|\n'+values.map(v=>'| '+v.map(x=>String(x??'—').replaceAll('|',' / ')).join(' | ')+' |').join('\n')+'\n\n';
  const catalogue=(id,heads,values,filters=[])=>`<section class="wiki-catalogue" data-catalogue="${id}"><div class="wiki-filters"><label for="${id}-search">Search this catalogue<input id="${id}-search" type="search" placeholder="Name, stat, school or keyword…"></label>${filters.map((f,i)=>`<label for="${id}-filter-${i}">${esc(f.label)}<select id="${id}-filter-${i}" data-column="${f.column}"><option value="">All ${esc(f.label.toLowerCase())}</option>${[...new Set(values.map(v=>v[f.column]))].sort().map(v=>`<option>${esc(v)}</option>`).join('')}</select></label>`).join('')}<button type="button" data-reset>Reset</button></div><p class="wiki-count" role="status">${values.length} entries</p><table><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${values.map(v=>`<tr>${v.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table><p data-empty hidden>No matching entries. Clear the search or filters.</p></section>`;
  const s=data.skilltree, nodes=new Map(s.nodes.map(n=>[n.id,n]));
  const bonus=n=>(n?.description||[]).map(d=>esc(d.text)).join('<br>')||'No stat bonus';
  const lookup=id=>nodes.get('skilltree:tk3_'+id);
  const req=n=>(n?.requirements||[]).map(r=>esc(nodes.get(r.skill_id)?.title||r.skill_id||r.type)).join(' + ')||'Starting node';
  const roles={warrior:'Melee damage, attack rhythm and durability.',ranger:'Ranged damage, precision and hunting.',rogue:'Critical hits, speed and evasive offence.',mage:'Mana and spell power, with elemental or hybrid specialisation.',cleric:'Holy magic, healing and resilient support.',occultist:'Blood, summons and eldritch power with explicit trade-offs.'};
  let skill='# Classes & professions\n\n**6 CLASSES · 18 SUBCLASSES · 7 PROFESSIONS · '+s.nodes.length+' NODES**\n\nShape your character through shared constellations, a class foundation and three subclass paths. This guide is generated from the supplied **v3.2.3 SIX PATHS** script. [Browse every node](../skill-nodes/) or jump to a class below.\n\n## How to choose your path\n\nStart at Adventurer’s Origin, travel through the shared tree and unlock a class root. Finish the class foundation to reach the mastery hub and Specialisation Gate. Choose your subclass, then invest along its three independent paths. Advanced class lobes are optional.\n\nEvery node costs **one point from the same point pool**. You may choose one class and one subclass. Profession masteries are limited to three; each profession allows three of its six focus nodes. Taking profession nodes is separate from choosing a class.\n\nThe script recommends an initial maximum of 260 points and describes an intended endgame spend of 150–220. These are design recommendations, not a verified server point cap.\n\n## Class overview\n';
  skill+=rows(['Class','Focus','Subclasses','Root bonus'],s.classes.map(c=>['['+c.name+'](#'+c.id+')',roles[c.id],c.subclasses.map(x=>x.name).join(', '),bonus(lookup(c.id+'_root'))]));
  skill+='## Reading stats and prerequisites\n\nBonuses below reproduce the script’s display text, including penalties. Percentage attributes, percentage-point chances and flat armour/reach values are different operations; do not add them all as flat percentages. Display values are rounded by the script. A node called Fury or Guard grants its listed statistics; its name alone does not add an Epic Fight move or an Ars spell.\n\nThe documentation extractor assumes the Minecraft, Iron’s Spellbooks and Apothic attributes exist. The script has fallbacks when optional attributes are missing. In-game tooltips and server configuration determine the actual loaded result.\n';
  for(const c of s.classes){
    skill+='## '+c.name+'\n\n'+roles[c.id]+' **Class root:** '+bonus(lookup(c.id+'_root'))+'.\n\n### '+c.name+' foundation\n';
    skill+=rows(['Lobe','Each inner rank','Each advanced rank'],c.core.map((x,i)=>[x[0],bonus(lookup(c.id+'_core_inner_'+(i+1)+'_1')),bonus(lookup(c.id+'_core_advanced_'+(i+1)+'_1'))]));
    const inner=s.nodes.filter(n=>n.id.startsWith('skilltree:tk3_'+c.id+'_core_inner_'));const advanced=s.nodes.filter(n=>n.id.startsWith('skilltree:tk3_'+c.id+'_core_advanced_'));
    skill+='The generated foundation has **'+inner.length+' inner nodes**; the optional advanced lobes add **'+advanced.length+' nodes**. **Mastery:** '+bonus(lookup(c.id+'_class_mastery'))+'. **Gate:** '+bonus(lookup(c.id+'_subclass_gate'))+'.\n\n';
    for(const sub of c.subclasses){const prefix=c.id+'_sub_'+sub.id;
      skill+='### '+sub.name+'\n\n**Entry bonuses and penalties:** '+bonus(lookup(prefix))+'.\n\n';
      skill+=rows(['Independent path','Bonus per rank','Length'],sub.traits.map((x,i)=>[x[0],bonus(lookup(prefix+'_path_'+(i+1)+'_1')),'14 sequential nodes']));
      skill+='Ranks 4 and 8 are notable nodes; rank 14 is the path apex. Their visual status does not multiply the listed rank bonus. Each path begins at the subclass root and requires its preceding rank; there are no cross-path shortcuts.\n\n';
      skill+=rows(['Optional / final node','Requires','Bonus'],[1,2].map(i=>lookup(prefix+'_synergy_'+i)).concat(lookup(prefix+'_ascendancy')).map(n=>[n.title,req(n),bonus(n)]));
      skill+='Synergies are optional dead ends. Ascendancy requires all three rank-14 apexes and the subclass root. Its listed penalties also apply.\n\n';
    }
  }
  skill+='## Shared constellations\n\nThese eight clusters support every class. They offer two main arms, mastery and additional general paths. Compare the individual bonuses in the node catalogue.\n';
  skill+=rows(['Constellation','Root','Mastery'],s.sharedDefs.map(x=>[x.name,bonus(lookup('shared_'+x.id+'_root')),bonus(lookup('shared_'+x.id+'_mastery'))]));
  skill+='## Professions & focus choices\n\nSeven profession islands have three branches each. Focus A and B are separate nodes with matching bonuses, and each requires rank 5 of its own branch. Choose at most three focuses per profession and three profession masteries across the whole tree.\n';
  for(const p of s.professions){skill+='### '+p.name+'\n';skill+=rows(['Branch','Focus A / B bonus','Focus prerequisite'],p.branches.map((b,i)=>{const n=lookup('prof_'+p.id+'_focus_'+(i*2+1));return [b[0],bonus(n),req(n)]}));}
  skill+='## Build planning\n\nChoose your intended role first, then compare the subclass entry penalties. Invest enough in the class foundation to unlock specialisation before spreading into optional lobes. A single subclass path is cheaper than the three-path Ascendancy route; plan your profession focuses around activities you actually use.\n\nFor a front-line build, compare Warrior’s Juggernaut with Cleric’s Crusader. For spellcasting, compare Mage’s mana and school paths with Cleric and Occultist. Battlemage is a Mage subclass; Juggernaut belongs to Warrior. These are planning suggestions, not a damage ranking.\n\n[Combat guide](../epic-fight/) · [Iron’s magic](../irons-spells/) · [Ars spellcraft](../ars-nouveau/)\n\n## Source & maintenance\n\nAuthoritative source: '+esc(s.source.name)+' · '+esc(s.source.version)+'. The old 3.2.2 and V1.0 design documents are not used for this guide. Extracted source SHA-256: `'+s.source.sha256+'`. [Download the documented node data](../../assets/wiki/skilltree.json).\n';
  function category(n){const id=n.id.replace('skilltree:tk3_','');for(const c of s.classes)if(id.startsWith(c.id+'_'))return c.name;for(const p of s.professions)if(id.startsWith('prof_'+p.id+'_'))return p.name;return 'Shared tree';}
  const nodeGuide='# Skill node catalogue\n\nSearch all '+s.nodes.length+' generated nodes by name, statistic or requirement. Bonuses and prerequisites come from the supplied v3.2.3 script. **One point per node.** [Read classes, paths and focus choices](../skill-tree/).\n\n## Every node\n\n'+catalogue('nodes',['Node','Area','Bonuses','Required skills','Node ID'],s.nodes.map(n=>[esc(n.title),category(n),bonus(n),req(n),'<code>'+esc(n.id)+'</code>']),[{label:'Area',column:1}]);
  const spells=data.spells;const spellGuide='# Spell catalogue\n\n**'+spells.entries.length+' REFERENCE SPELL DEFINITIONS**\n\nSearch spell names, schools and casting modes across Iron’s Spellbooks and the documented addons. [Learn how spellbooks work](../irons-spells/).\n\n## Coverage and versions\n\n'+esc(spells.coverage)+' This is an upstream reference catalogue, not a promise that every source definition is enabled in Alpha 1.0. The alpha mod list identifies projects but no jar versions. For exact availability, cost, cooldown, level and damage, inspect the installed spell tooltip and JEI.\n\n## Browse spells\n\n'+catalogue('spells',['Spell','Mod','School','Cast','Reference'],spells.entries.map(x=>[esc(x.name),esc(x.mod),esc(x.school),esc(x.cast),'<a href="'+esc(x.source)+'">Author source</a>']),[{label:'Mod',column:1},{label:'School',column:2},{label:'Cast',column:3}]);
  const glyphGuide='# Ars glyph catalogue\n\n**'+data.glyphs.entries.length+' CORE GLYPHS**\n\nCombine a method, effects and compatible augments to design your spells. [Read the spellcraft guide](../ars-nouveau/).\n\n## Reference coverage\n\n'+esc(data.glyphs.coverage)+' These are definitions in the pinned upstream branch; the installed book determines unlock recipes and availability.\n\n## Browse glyphs\n\n'+catalogue('glyphs',['Glyph','Type','Default tier','Compatible augments in source','Reference'],data.glyphs.entries.map(x=>[esc(x.name),esc(x.type),esc(x.tier),esc(x.compatibleAugments.join(', '))||'Check glyph tooltip / inherited behaviour','<a href="'+esc(x.source)+'">Author source</a>']),[{label:'Type',column:1},{label:'Default tier',column:2}]);
  const accessoryGuide='# Accessory catalogue\n\n**'+data.accessories.entries.length+' CORE ITEM NAMES**\n\n[Read Artifacts, Relics and their integrations](../artifacts-relics/).\n\n## Reference coverage\n\n'+esc(data.accessories.coverage)+' Names include core utility items as well as equippable relics; this index does not label every entry as a loot drop.\n\n## Browse accessories\n\n'+catalogue('accessories',['Item','Mod','Registry ID','Reference'],data.accessories.entries.map(x=>[esc(x.name),esc(x.mod),'<code>'+esc(x.id)+'</code>','<a href="'+esc(x.source)+'">Author source</a>']),[{label:'Mod',column:1}]);
  const witcheryGuide='# Witchery topic index\n\n**'+data['witchery-book'].entries.length+' BOOK TOPICS**\n\nFind the section to open in the installed Modonomicon guide. [Read the Witchery starter guide](../witchery/).\n\n## Reference coverage\n\n'+esc(data['witchery-book'].coverage)+' Reference release: **'+esc(data['witchery-book'].release)+'**. [Author release]('+data['witchery-book'].source+'). This index identifies topics; it does not reproduce the author’s book text.\n\n## Browse topics\n\n'+catalogue('witchery',['Topic','Book category','Entry ID'],data['witchery-book'].entries.map(x=>[esc(x.name),esc(x.category.replaceAll('_',' ')),'<code>'+esc(x.id)+'</code>']),[{label:'Book category',column:1}]);
  const modGuide='# Alpha 1.0 mod list\n\n**'+data['alpha-mods'].entries.filter(x=>x.kind==='Mod').length+' MOD PROJECTS · '+data['alpha-mods'].entries.filter(x=>x.kind==='Resource pack').length+' RESOURCE PACK**\n\nThe current selection comes exclusively from **modlist.html** in the supplied Alpha 1.0 export. Earlier candidate lists do not override this list. '+esc(data['alpha-mods'].versionCoverage)+'\n\n## Browse the complete alpha list\n\n'+catalogue('mods',['Project','Author','Type','Documentation / project'],data['alpha-mods'].entries.map(x=>[esc(x.name),esc(x.author),x.kind,'<a href="'+esc(x.url)+'">Author project</a>']),[{label:'Type',column:2}])+'\n\n## Related references\n\n[Magic guides](../magic/) · [Combat](../epic-fight/) · [Accessories](../artifacts-relics/) · [Classes & professions](../skill-tree/)\n\nSelection notes and the legacy comparison preserve earlier development decisions. They are not the Alpha 1.0 inventory.\n';
  return {skill,nodeGuide,spellGuide,glyphGuide,accessoryGuide,witcheryGuide,modGuide};
};
