// Full restart required. Supplied assets; quest icons have no recipes.
StartupEvents.registry("item", event => {
    event.create("tk3_quest_bell")
        .displayName("Bell")
        .texture("kubejs:tk3_supplied/quests_info/bell");
    event.create("tk3_quest_book")
        .displayName("Book")
        .texture("kubejs:tk3_supplied/quests_info/book");
    event.create("tk3_quest_bookopen")
        .displayName("Bookopen")
        .texture("kubejs:tk3_supplied/quests_info/bookopen");
    event.create("tk3_quest_bookred")
        .displayName("Bookred")
        .texture("kubejs:tk3_supplied/quests_info/bookred");
    event.create("tk3_quest_buyorderblue")
        .displayName("Buyorderblue")
        .texture("kubejs:tk3_supplied/quests_info/buyorderblue");
    event.create("tk3_quest_buyorderdarkblue")
        .displayName("Buyorderdarkblue")
        .texture("kubejs:tk3_supplied/quests_info/buyorderdarkblue");
    event.create("tk3_quest_buyordergreen")
        .displayName("Buyordergreen")
        .texture("kubejs:tk3_supplied/quests_info/buyordergreen");
    event.create("tk3_quest_buyordergrey")
        .displayName("Buyordergrey")
        .texture("kubejs:tk3_supplied/quests_info/buyordergrey");
    event.create("tk3_quest_buyorderred")
        .displayName("Buyorderred")
        .texture("kubejs:tk3_supplied/quests_info/buyorderred");
    event.create("tk3_quest_buyorderwhite")
        .displayName("Buyorderwhite")
        .texture("kubejs:tk3_supplied/quests_info/buyorderwhite");
    event.create("tk3_quest_buyorderyellow")
        .displayName("Buyorderyellow")
        .texture("kubejs:tk3_supplied/quests_info/buyorderyellow");
    event.create("tk3_quest_candle")
        .displayName("Candle")
        .texture("kubejs:tk3_supplied/quests_info/candle");
    event.create("tk3_quest_coffee")
        .displayName("Coffee")
        .texture("kubejs:tk3_supplied/quests_info/coffee");
    event.create("tk3_quest_cup")
        .displayName("Cup")
        .texture("kubejs:tk3_supplied/quests_info/cup");
    event.create("tk3_quest_drum")
        .displayName("Drum")
        .texture("kubejs:tk3_supplied/quests_info/drum");
    event.create("tk3_quest_envelope")
        .displayName("Envelope")
        .texture("kubejs:tk3_supplied/quests_info/envelope");
    event.create("tk3_quest_feather")
        .displayName("Feather")
        .texture("kubejs:tk3_supplied/quests_info/feather");
    event.create("tk3_quest_flute")
        .displayName("Flute")
        .texture("kubejs:tk3_supplied/quests_info/flute");
    event.create("tk3_quest_hammer")
        .displayName("Hammer")
        .texture("kubejs:tk3_supplied/quests_info/hammer");
    event.create("tk3_quest_harp")
        .displayName("Harp")
        .texture("kubejs:tk3_supplied/quests_info/harp");
    event.create("tk3_quest_herb")
        .displayName("Herb")
        .texture("kubejs:tk3_supplied/quests_info/herb");
    event.create("tk3_quest_herbtwo")
        .displayName("Herbtwo")
        .texture("kubejs:tk3_supplied/quests_info/herbtwo");
    event.create("tk3_quest_horn")
        .displayName("Horn")
        .texture("kubejs:tk3_supplied/quests_info/horn");
    event.create("tk3_quest_hourglass")
        .displayName("Hourglass")
        .texture("kubejs:tk3_supplied/quests_info/hourglass");
    event.create("tk3_quest_info")
        .displayName("Info")
        .texture("kubejs:tk3_supplied/quests_info/info");
    event.create("tk3_quest_jar")
        .displayName("Jar")
        .texture("kubejs:tk3_supplied/quests_info/jar");
    event.create("tk3_quest_job_bard")
        .displayName("Job Bard")
        .texture("kubejs:tk3_supplied/quests_info/job_bard");
    event.create("tk3_quest_job_brewer")
        .displayName("Job Brewer")
        .texture("kubejs:tk3_supplied/quests_info/job_brewer");
    event.create("tk3_quest_job_cook")
        .displayName("Job Cook")
        .texture("kubejs:tk3_supplied/quests_info/job_cook");
    event.create("tk3_quest_job_explorer")
        .displayName("Job Explorer")
        .texture("kubejs:tk3_supplied/quests_info/job_explorer");
    event.create("tk3_quest_job_farmer")
        .displayName("Job Farmer")
        .texture("kubejs:tk3_supplied/quests_info/job_farmer");
    event.create("tk3_quest_job_fighter")
        .displayName("Job Fighter")
        .texture("kubejs:tk3_supplied/quests_info/job_fighter");
    event.create("tk3_quest_job_fisherman")
        .displayName("Job Fisherman")
        .texture("kubejs:tk3_supplied/quests_info/job_fisherman");
    event.create("tk3_quest_job_lumberjack")
        .displayName("Job Lumberjack")
        .texture("kubejs:tk3_supplied/quests_info/job_lumberjack");
    event.create("tk3_quest_job_miner")
        .displayName("Job Miner")
        .texture("kubejs:tk3_supplied/quests_info/job_miner");
    event.create("tk3_quest_jobs")
        .displayName("Jobs")
        .texture("kubejs:tk3_supplied/quests_info/jobs");
    event.create("tk3_quest_journal")
        .displayName("Journal")
        .texture("kubejs:tk3_supplied/quests_info/journal");
    event.create("tk3_quest_key")
        .displayName("Key")
        .texture("kubejs:tk3_supplied/quests_info/key");
    event.create("tk3_quest_lantern")
        .displayName("Lantern")
        .texture("kubejs:tk3_supplied/quests_info/lantern");
    event.create("tk3_quest_logo")
        .displayName("Logo")
        .texture("kubejs:tk3_supplied/quests_info/logo");
    event.create("tk3_quest_lute")
        .displayName("Lute")
        .texture("kubejs:tk3_supplied/quests_info/lute");
    event.create("tk3_quest_map")
        .displayName("Map")
        .texture("kubejs:tk3_supplied/quests_info/map");
    event.create("tk3_quest_mirror")
        .displayName("Mirror")
        .texture("kubejs:tk3_supplied/quests_info/mirror");
    event.create("tk3_quest_mortar")
        .displayName("Mortar")
        .texture("kubejs:tk3_supplied/quests_info/mortar");
    event.create("tk3_quest_musicbox")
        .displayName("Musicbox")
        .texture("kubejs:tk3_supplied/quests_info/musicbox");
    event.create("tk3_quest_nightmarket")
        .displayName("Nightmarket")
        .texture("kubejs:tk3_supplied/quests_info/nightmarket");
    event.create("tk3_quest_ocerina")
        .displayName("Ocerina")
        .texture("kubejs:tk3_supplied/quests_info/ocerina");
    event.create("tk3_quest_paper")
        .displayName("Paper")
        .texture("kubejs:tk3_supplied/quests_info/paper");
    event.create("tk3_quest_pickaxe")
        .displayName("Pickaxe")
        .texture("kubejs:tk3_supplied/quests_info/pickaxe");
    event.create("tk3_quest_plantfour")
        .displayName("Plantfour")
        .texture("kubejs:tk3_supplied/quests_info/plantfour");
    event.create("tk3_quest_plantone")
        .displayName("Plantone")
        .texture("kubejs:tk3_supplied/quests_info/plantone");
    event.create("tk3_quest_plantthree")
        .displayName("Plantthree")
        .texture("kubejs:tk3_supplied/quests_info/plantthree");
    event.create("tk3_quest_planttwo")
        .displayName("Planttwo")
        .texture("kubejs:tk3_supplied/quests_info/planttwo");
    event.create("tk3_quest_poison")
        .displayName("Poison")
        .texture("kubejs:tk3_supplied/quests_info/poison");
    event.create("tk3_quest_ponder_stone_generation")
        .displayName("Ponder Stone Generation")
        .texture("kubejs:tk3_supplied/quests_info/ponder_stone_generation");
    event.create("tk3_quest_pot")
        .displayName("Pot")
        .texture("kubejs:tk3_supplied/quests_info/pot");
    event.create("tk3_quest_potionblue")
        .displayName("Potionblue")
        .texture("kubejs:tk3_supplied/quests_info/potionblue");
    event.create("tk3_quest_potionbluethree")
        .displayName("Potionbluethree")
        .texture("kubejs:tk3_supplied/quests_info/potionbluethree");
    event.create("tk3_quest_potionbluetwo")
        .displayName("Potionbluetwo")
        .texture("kubejs:tk3_supplied/quests_info/potionbluetwo");
    event.create("tk3_quest_potionred")
        .displayName("Potionred")
        .texture("kubejs:tk3_supplied/quests_info/potionred");
    event.create("tk3_quest_potionredthree")
        .displayName("Potionredthree")
        .texture("kubejs:tk3_supplied/quests_info/potionredthree");
    event.create("tk3_quest_potionredtwo")
        .displayName("Potionredtwo")
        .texture("kubejs:tk3_supplied/quests_info/potionredtwo");
    event.create("tk3_quest_questboard")
        .displayName("Questboard")
        .texture("kubejs:tk3_supplied/quests_info/questboard");
    event.create("tk3_quest_questcalculation")
        .displayName("Questcalculation")
        .texture("kubejs:tk3_supplied/quests_info/questcalculation");
    event.create("tk3_quest_questcomplete")
        .displayName("Questcomplete")
        .texture("kubejs:tk3_supplied/quests_info/questcomplete");
    event.create("tk3_quest_questcreative")
        .displayName("Questcreative")
        .texture("kubejs:tk3_supplied/quests_info/questcreative");
    event.create("tk3_quest_questender")
        .displayName("Questender")
        .texture("kubejs:tk3_supplied/quests_info/questender");
    event.create("tk3_quest_questequipment")
        .displayName("Questequipment")
        .texture("kubejs:tk3_supplied/quests_info/questequipment");
    event.create("tk3_quest_questextra")
        .displayName("Questextra")
        .texture("kubejs:tk3_supplied/quests_info/questextra");
    event.create("tk3_quest_questinductive")
        .displayName("Questinductive")
        .texture("kubejs:tk3_supplied/quests_info/questinductive");
    event.create("tk3_quest_questinfernal")
        .displayName("Questinfernal")
        .texture("kubejs:tk3_supplied/quests_info/questinfernal");
    event.create("tk3_quest_questlifesaver")
        .displayName("Questlifesaver")
        .texture("kubejs:tk3_supplied/quests_info/questlifesaver");
    event.create("tk3_quest_questmarket")
        .displayName("Questmarket")
        .texture("kubejs:tk3_supplied/quests_info/questmarket");
    event.create("tk3_quest_questnext")
        .displayName("Questnext")
        .texture("kubejs:tk3_supplied/quests_info/questnext");
    event.create("tk3_quest_questprecision")
        .displayName("Questprecision")
        .texture("kubejs:tk3_supplied/quests_info/questprecision");
    event.create("tk3_quest_questrotation")
        .displayName("Questrotation")
        .texture("kubejs:tk3_supplied/quests_info/questrotation");
    event.create("tk3_quest_questrpgeight")
        .displayName("Questrpgeight")
        .texture("kubejs:tk3_supplied/quests_info/questrpgeight");
    event.create("tk3_quest_questrpgfive")
        .displayName("Questrpgfive")
        .texture("kubejs:tk3_supplied/quests_info/questrpgfive");
    event.create("tk3_quest_questrpgfour")
        .displayName("Questrpgfour")
        .texture("kubejs:tk3_supplied/quests_info/questrpgfour");
    event.create("tk3_quest_questrpgnine")
        .displayName("Questrpgnine")
        .texture("kubejs:tk3_supplied/quests_info/questrpgnine");
    event.create("tk3_quest_questrpgone")
        .displayName("Questrpgone")
        .texture("kubejs:tk3_supplied/quests_info/questrpgone");
    event.create("tk3_quest_questrpgseven")
        .displayName("Questrpgseven")
        .texture("kubejs:tk3_supplied/quests_info/questrpgseven");
    event.create("tk3_quest_questrpgsix")
        .displayName("Questrpgsix")
        .texture("kubejs:tk3_supplied/quests_info/questrpgsix");
    event.create("tk3_quest_questrpgten")
        .displayName("Questrpgten")
        .texture("kubejs:tk3_supplied/quests_info/questrpgten");
    event.create("tk3_quest_questrpgthree")
        .displayName("Questrpgthree")
        .texture("kubejs:tk3_supplied/quests_info/questrpgthree");
    event.create("tk3_quest_questrpgtwo")
        .displayName("Questrpgtwo")
        .texture("kubejs:tk3_supplied/quests_info/questrpgtwo");
    event.create("tk3_quest_quests")
        .displayName("Quests")
        .texture("kubejs:tk3_supplied/quests_info/quests");
    event.create("tk3_quest_questseared")
        .displayName("Questseared")
        .texture("kubejs:tk3_supplied/quests_info/questseared");
    event.create("tk3_quest_questspace")
        .displayName("Questspace")
        .texture("kubejs:tk3_supplied/quests_info/questspace");
    event.create("tk3_quest_queststeel")
        .displayName("Queststeel")
        .texture("kubejs:tk3_supplied/quests_info/queststeel");
    event.create("tk3_quest_root")
        .displayName("Root")
        .texture("kubejs:tk3_supplied/quests_info/root");
    event.create("tk3_quest_rope")
        .displayName("Rope")
        .texture("kubejs:tk3_supplied/quests_info/rope");
    event.create("tk3_quest_sack")
        .displayName("Sack")
        .texture("kubejs:tk3_supplied/quests_info/sack");
    event.create("tk3_quest_satchel")
        .displayName("Satchel")
        .texture("kubejs:tk3_supplied/quests_info/satchel");
    event.create("tk3_quest_scroll")
        .displayName("Scroll")
        .texture("kubejs:tk3_supplied/quests_info/scroll");
    event.create("tk3_quest_shovel")
        .displayName("Shovel")
        .texture("kubejs:tk3_supplied/quests_info/shovel");
    event.create("tk3_quest_skill_point")
        .displayName("Skill Point")
        .texture("kubejs:tk3_supplied/quests_info/skill_point");
    event.create("tk3_quest_skill_reset")
        .displayName("Skill Reset")
        .texture("kubejs:tk3_supplied/quests_info/skill_reset");
    event.create("tk3_quest_torch")
        .displayName("Torch")
        .texture("kubejs:tk3_supplied/quests_info/torch");
});
