from pathlib import Path
import json,re,collections
ROOT=Path(__file__).resolve().parents[1]
m=json.loads((ROOT/'docs/progression_manifest.json').read_text())
groups={
'Create & integrations':[
('Create','1–10','Mechanical production, sequenced mechanisms, frames and logistics'),('Enchantment Industry','3–5','XP collection, printing, enchanting and liquid XP devices'),('Slice & Dice','1–2','Farmer’s Delight cutting, irrigation and fertilizer'),('Crafts & Additions','2–4','Rolling, capacitors and the rotational-power/FE bridge'),('MineColonies Link','3–7','Colony supply requests connected to Create logistics'),('Sophisticated Storage Create Integration','1–10','Supported storage upgrades on Create contraptions; integration has no new recipe-bearing items'),('Create: Ars Nouveau Compat','4–7','Source processing and actual Source-powered machine upgrades'),('Dragons Plus','2–5','Fluid hatch, native freezing/ending processing and Dragon’s Breath'),('Aeronautics','3 / 7','Early stationary propellers; chapter 7 flight controls and expedition vessels'),('Compat Core','1–10','Shared addon support; no invented progression items'),('Hypertubes','3','Brass transport, frame-based entrances and accelerators'),('Wizardry','4–7','Arcane casing, Mana, runes, sheets and Iron’s processing'),('Aquatic Ambitions','2','Calcium feed, prismarine alloy, conduit cage and native channeling')],
'Technology':[
('Mekanism','4–10','First infusing and refining at 4, advanced factories at 5, gases/HDPE at 6, fission at 8 and SPS/fusion at 9'),('Mekanism Generators','4–9','First Heat Generator, later renewables, gas power, turbine, fission and fusion'),('Mekanism Tools','4–6','Native tools and preserving paxels; Steel Paxel finishes the Chemical workshop sequence'),('Aeronautics Mekanism Compat','7–10','Mekanism systems on the moving expedition vessel'),('Applied Energistics 2','4–10','1k cells and network at 4; 4k at 6, 16k at 7, spatial at 8, 64k/quantum at 9, 256k at 10'),('Applied Mekanistics','6–10','Chemical cells, portable chemical cells and native preserving upgrades')],
'Magic':[
('Ars Nouveau','1 / 4–10','Native early Source and character tools; parallel Arcane workshop from 4'),('Ars Creo','4–7','Ars contraptions and Starbuncle Wheel'),('Iron’s Spells ’n Spellbooks','1 / 4–10','Native combat spells; factory cauldron, ink and arcane processing from 4'),('Iron’s Gems ’n Jewelry','2–10','Copper workshop Jewelcrafting Station; native jewels, scrolls and jewelry data')],
'World, building & equipment':[
('Architect’s Palette','1','Real Algal Blend and decorative materials'),('Apotheosis','4–10','Affix, gem and socket equipment alongside the factory; native loot and forging mechanics'),('Sophisticated Storage & Backpacks','1–10','Early collection and processing, tiered upgrades, preserving storage contents'),('Ice & Fire','7–8','Exploration and chapter 8 dragonforge workshops; corresponding dragon is still required'),('Cataclysm','7–9','Harbinger, Ignis and Ender Guardian permanent cores'),('Bosses’ Rise','1–10','Optional combat and exploration; no invented mob IDs or mandatory unverified drops'),('Alex’s Mobs','1–10','Wildlife and optional resource/exploration branches'),('Alex’s Caves','7–8','Expedition mining and late cave machinery'),('Farmer’s Delight','1–6','Food, cutting, crop integration, seals and Bio Fuel feedstock'),('Waystones','4–10','Travel alongside ships and quantum links'),('MineColonies','1 / 3–10','Settlement growth; brass logistics and supply integration'),('Upgrade Aquatic','2','Aquatic ecosystem linked with Aquatic Ambitions'),('Chipped','1','Frame-based decorative workbenches; decorative variants remain native'),('Mowzie’s Mobs','1–10','Optional encounters and native rewards'),('Twilight Forest','6','Twilight exploration and permanent Lich Sigil'),('AStages','1–10','Team milestone sync, device tiers, Nether at 3 and End at 5'),('Amendments','1–10','Useful native block interactions; no separate progression machinery'),('Supplementaries','1–10','Useful building, storage and interaction tools with native recipes')],
'KubeJS & support':[
(n,'1–10',role)for n,role in [
('KubeJS Ponder','Client tutorial authoring support; the website workshop shows the current exact recipes'),('LootJS','Player-kill modifiers for permanent boss cores'),('KubeJS Tweaks','Shared scripting and recipe support'),('KubeJS Curios','Equipment integration support; no custom slot progression added here'),('KubeJS Iron’s Spells','Cauldron brewing and bottling'),('KubeJS Mekanism','Native industrial processing and chemical schemas'),('KubeJS Ars Nouveau','Apparatus and Source recipes'),('Applied KubeJS','AE2 Charger and Inscriber processing'),('Create Heat JS','Heat scripting support; current alloy bootstraps use reachable Blaze heat'),('KubeJS Create','Sequenced assembly, deployment, stone and wood processing')]]}
doc='# T&K3 · MODS & THEIR TIERS\n\n**10 CHAPTERS · '+str(m['quest_count'])+' QUESTS · '+str(len(m['recipes']))+' RECIPES**\n\nThe current progression selection is grouped by its actual workshop role. Native world, combat and building systems remain available alongside the chapter spine. Integration libraries do not need artificial crafting items to earn a place in the pack.\n\n'
entries=[]
for group,rows in groups.items():
 doc+='## '+group+'\n\n| Mod / integration | Chapter | Role |\n|---|---|---|\n'
 for n,t,role in rows:
  doc+='| **'+n+'** | '+t+' | '+role+' |\n';entries.append(dict(name=n,group=group,tier=t,role=role,status='Selected'))
 doc+='\n'
doc+='## First machines before new materials\n\n- **Chapter 4:** heated steel → Steel Casing → Precision Mechanism deployment → Infuser. Charger and Inscriber precede the Inductive Machine.\n- **Chapter 6:** Ender Machines build the first separator, rotary machine and PRC; these produce HDPE before the Chemical Machine.\n- **Chapter 9:** Containment Frames build the first SPS and Nucleosynthesizer; these produce antimatter and Stargaze before the Singularity Frame.\n\n**[TEN CHAPTER PATHS →](https://mikaaah.github.io/TownsAndKingdoms/progression/#paths)** · [All quests](https://mikaaah.github.io/TownsAndKingdoms/chapters/)\n'
(ROOT/'docs/MOD_TIER_MAP_EN.md').write_text(doc)
audit=dict(source='User progression selection, 2026-10-03; native addon sources recorded in progression_manifest.json',entries=entries,status_counts={'Selected':len(entries)},recipes=len(m['recipes']),chapters=10,quests=m['quest_count'])
(ROOT/'docs/mod_tier_audit.json').write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n')
p=ROOT/'docs/MODLIST.md';s=p.read_text();s=s.replace('- Just Another Witchery Remake','- Iron’s Gems ’n Jewelry');s=s.replace('### Just Another Witchery Remake\n- Curios API\n- Kotlin for Forge\n- Modonomicon\n\n','')
s=re.sub(r'## Selected Create / technology integrations[\s\S]*?(?=## Progression / compatibility integrations)', '## Selected Create / technology integrations\n\nThe updated progression selection uses the following integrations. Exact recipe routes and chapters are recorded in [Mods & tiers](https://mikaaah.github.io/TownsAndKingdoms/3.0/tier-map/).\n\n'+''.join('- '+n+'\n'for group in ['Create & integrations','Technology','KubeJS & support']for n,t,role in groups[group])+'\n---\n\n',s)
s=re.sub(r'### Magic / content bridges[\s\S]*?(?=### Apotheosis bridges)', '### Magic / content bridges\n- Ars Creo\n- Create: Ars Nouveau Compat\n- Create: Wizardry\n- Iron’s Gems ’n Jewelry\n\n',s)
s=s.replace('Mekanism is a later technology layer rather than an immediate replacement for Create.','Mekanism begins in chapter 4 alongside AE2; advanced factories follow End access in chapter 5.').replace('Applied Energistics 2 is the main late-game storage, logistics and autocrafting network.','Applied Energistics 2 starts with the chapter 4 network and grows through chemical, spatial and quantum logistics.')
for n in ['Architect’s Palette','Sophisticated Storage','Sophisticated Backpacks','Farmer’s Delight','Chipped','Amendments','Supplementaries','Mekanism Tools']:
 if not re.search(r'^- '+re.escape(n)+'$',s,re.M):s+='\n- '+n+'\n'
s=s.replace('### Engineering & Automation\n','### Engineering & Automation\n- Mekanism Tools\n- Slice & Dice\n- Aquatic Ambitions\n- Hypertubes\n')
(ROOT/'docs/MODLIST.md').write_text(s)
p=ROOT/'tools/build_handbook.cjs';s=p.read_text();s=s.replace("['overview','frames','paths','compat','tips']","['overview','frames','paths','geology','wood']")
s=s.replace('**Create Crafts & Additions**, **Ars Creo**, **Create: Ars Nouveau Compat**, **Create: Wizardry** and **Create: MineColonies Link** are selected connections between the main systems.','**Slice & Dice**, **Crafts & Additions**, **Aquatic Ambitions**, **Dragons Plus**, **Hypertubes**, **Ars Creo**, **Wizardry**, **MineColonies Link**, **Sophisticated Storage Create Integration** and **Applied Mekanistics** connect the workshop systems. Read [mods & tiers](../tier-map/) for the full selected progression stack.')
s=s.replace('The workshop is a website walkthrough, not a Minecraft Ponder addon.','The workshop is a website walkthrough. KubeJS Ponder is selected separately for in-game tutorial authoring.')
s=s.replace('↑','↑');p.write_text(s)
p=ROOT/'handbook-source/workshop.js';s=p.read_text().replace('All four boss cores are retained.','All five boss cores are retained.');p.write_text(s)
# Update local installation and maintainer entry points; the skill tree is unchanged.
(ROOT/'README.md').write_text('# Towns & Kingdoms 3 · Chapters I–X\n\n**'+str(len(m['recipes']))+' managed recipes · '+str(m['quest_count'])+' quests · 10 chapters · '+str(m['quest_icon_count'])+' quest/info items**\n\n[Official wiki](https://mikaaah.github.io/TownsAndKingdoms/) · [Recipe paths](docs/PLAYER_PATHS_EN.md) · [Mod tier map](docs/MOD_TIER_MAP_EN.md)\n\nInstall `kubejs/` and `config/ftbquests/` together into the Minecraft 1.21.1 NeoForge instance, then fully restart the client and server. Nether entry starts at chapter 3, AE2 and Mekanism at 4, End entry at 5. Chapters and milestone IDs remain stable; internal quest goals are updated for the new campaign.\n\nEdit the canonical `docs/progression_manifest.json`, run `tools/rebuild_recipes.py`, then `tools/format_recipes.py --pack TK3`. Regenerate English guide content and the handbook before publication. Player pages keep the current website template and styles. Runtime checks and limitations belong in [campaign maintenance](docs/CAMPAIGN_MAINTENANCE.md).\n')
print('Mapped',len(entries),'selected mods and integrations')
